### PR TITLE
Feat/#a4k5ay #a6k6m2

### PR DESCRIPTION
**Pull request by Kevinjhlin**
Add top right corner svg for create and edit bill

### CODE REVIEW

**Comment by dannylekim** [comment]
Task linked: [CU-a6k6m2 Top-right SVG](https://app.clickup.com/t/a6k6m2)

**Comment by dannylekim** [comment]
Task linked: [CU-a4k5ay Create Bills [5 POINTS]](https://app.clickup.com/t/a4k5ay)

**Review by alphakennyn — CHANGES_REQUESTED** [review]
Why don't you add `CreateBillBackground` files inside the `Background` folder?

**Comment by dannylekim** [comment]
@alphakennyn with this failing test,I can argue that a snapshot of an SVG isn't necessary so maybe we could just remove it?

**Comment by alphakennyn** [comment]
> @alphakennyn with this failing test,I can argue that a snapshot of an SVG isn't necessary so maybe we could just remove it? 

Yeah, let's just skip it. `it.skip`

**Comment by dannylekim** [comment]
@alphakennyn is this fine or nah

**Review by alphakennyn — APPROVED** [review]

**Pull request merged**
