### PR TITLE
feat(#a4k5ay_#a6k6a5): Add SVG on top right corner

### PR DESCRIPTION
**Pull request by Kevinjhlin**
SVG for the top right corner of the CreateBill and EditBill modal

### CODE REVIEW

**Comment by dannylekim** [comment]
Task linked: [CU-a6k6m2 Top-right SVG](https://app.clickup.com/t/a6k6m2)

**Comment by dannylekim** [comment]
Task linked: [CU-a4k5ay Create Bills [5 POINTS]](https://app.clickup.com/t/a4k5ay)

**Comment by dannylekim** [comment]
Task linked: [CU-a6k6a5 Display User data matching figma design](https://app.clickup.com/t/a6k6a5)

**Comment by thien-ng** [comment]
image
 @Kevinjhlin

**Review by dannylekim — APPROVED** [review]
Consider fixing the code smells, but otherwise looks good

**Pull request closed without merging**
